server:
  port: 1008
  context-path: /

# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_springcloud
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    hostname: localhost  #eureka客户端主机实例名称
    appname: springcloudprovider  #客户端服务名
    instance-id: springcloudprovider:1008 #客户端实例名称
    prefer-ip-address: true #显示IP
  client:
    service-url:
#      defaultZone: http://localhost:2001/eureka   #把服务注册到eureka注册中心
       defaultZone: http://2001服务器ip:2001/eureka/,http://2003服务器ip:2002/eureka/,http://2003服务器ip:2003/eureka/ # 集群

info:
   groupId: $project.groupId$
   artifactId: $project.artifactId$
   version: $project.version$
   负责人: 张三疯
   联系电话: 88888110