server:
  port: 81
  context-path: /

eureka:
  client:
    register-with-eureka: false #false 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    service-url:
      defaultZone: http://2001服务器ip:2001/eureka/,http://2003服务器ip:2002/eureka/,http://2003服务器ip:2003/eureka/ # 集群
